#spring:
#  jdbc:
#    username: root
#    password: 01184510
#    driverClassName: com.mysql.cj.jdbc.Driver1
#    url: 222
#配置使用哪个yml环境
spring:
  datasource:
    username: root
    password: '01184510'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/denglu?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    host: 192.168.10.105
    database: 0
    port: 6379
    password:
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
          #连接超时时间
      timeout: 10000


#  profiles:
#    active: dev
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'  # 对外暴露的访问入口 , 默认是/health和/info
#      base-path: /monitor # 默认是actuator
#  endpoint:
#    health:
#      show-details: ALWAYS	# 显示所有健康状态
#  server:
#    port: 9999